### ISSUE TITLE
how to install bkg.json 

### ISSUE THREAD

**Issue by almoharebh** [IonicaBizau/package.json#11]
I try to install pkg.json but not install 
I  don't know how to use git init

**Comment by IonicaBizau** [comment]
What is the specific error you get?

**Comment by almoharebh** [comment]
npm WARN package.json string@1.0.0 No README data
npm WARN package.json JSV@4.0.2 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.
npm WARN package.json curl@0.1.4 No repository field.
npm WARN package.json nodejs@0.0.0 No repository field.
npm WARN package.json pad-component@0.0.1 No repository field.
npm WARN package.json template-copy@1.1.2 No repository field.

**Comment by IonicaBizau** [comment]
These are warnings... They are not harmful.

**Comment by almoharebh** [comment]
package.json cannot read from this  file

**Comment by almoharebh** [comment]
$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (api-v1-client-ruby) package.json
version: (1.0.0)
description: git-package-json
entry point: (index.js) index.js
test command: npm test
git repository: (https://github.com/blockchain/api-v1-client-ruby) https://github.com/IonicaBizau/git-package-json.git
can you tell me please how can i setup this

**Comment by almoharebh** [comment]
package.json@1.0.0 test C:\Users\sub-user
> echo "Error: no test specified" && exit 1

**Comment by IonicaBizau** [comment]
Sorry, this is not related to `pkg.json`
