### ISSUE TITLE
unpublish or namespace?

### ISSUE THREAD

**Issue by worc** [IonicaBizau/package.json#13]
npm and yarn seem to try to install this package if you're unlucky enough to have someone try to run `npm install package.json` or `yarn add package.json`. maybe this should be unpublished or namespaced so that people can't accidentally install it?

**Comment by sudar400** [comment]
:\Users\483141\Desktop\node-learn>npm install  package.json-server
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/package.json-server - Not found
npm ERR! 404
npm ERR! 404  'package.json-server@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\483141\AppData\Roaming\npm-cache\_logs\2019-12-19T06_23_02_006Z-debug.log

**Comment by worc** [comment]
yeah, that ☝️ 

@IonicaBizau 

whenever someone makes the mistake/typo of installing `package.json` of some kind, they're led here. this package needs to be unpublished or namespaced.

**Comment by IonicaBizau** [comment]
Well, `npm i package.json` should install the `package.json` package — I assume that is the supposed behaviour. I deprecated the `package.json` package in favor of `pkg.json`.

**Comment by worc** [comment]
it's an unexpected behavior. and it's still happening with `npm` and `yarn`. and it's borderline malicious to typosquat like that...

**Comment by IonicaBizau** [comment]
Why do you consider it unexpected?

**Comment by worc** [comment]
the `npm install <folder>` option implies an `npm install <local package.json file>` syntax, which this package typosquats on.

**Comment by IonicaBizau** [comment]
Is that implication documented somewhere? In this context `folder`, would be a directory pathname, not a file.

**Comment by worc** [comment]
this issue, and the follow up from @sudar400 are documentation of people making that assumption. i imagine there are a lot of erroneous installations of this package.
