### ISSUE TITLE
Readme on NPM is out of date

### ISSUE THREAD

**Issue by michaelcarter** [IonicaBizau/package.json#5]
Your readme on NPM states you install this package with: 

```
$ npm i --save package.json
```

Which as I'm sure you know is incorrect. I think a re-publish should bring it inline with what you have here in Github?

**Comment by IonicaBizau** [comment]
Well, that's obvious, because I published a new package: `pkg.json`. Since that's confusing, I took care of it and it should be fixed now. :rocket: :memo:
